language: python
python:
    - "2.7"
# http://stackoverflow.com/questions/15674064/github-submodule-access-rights-travis-ci
cache: apt
git:
    submodules: false
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
install:
    # - "sudo apt-get install s3cmd"
    - "sudo apt-get install -qq pandoc"
    - "pip install -r requirements.txt"
script: "pelican content/"
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: www.gregreda.com
    endpoint: http://www.gregreda.com.s3-website-us-east-1.amazonaws.com
    region: us-east-1
    skip_cleanup: true
    local-dir: output
    acl: public_read
    detect_encoding: true
    default_text_charset: 'utf-8'
after_deploy:
    # update cloudfront
    - "aws configure set preview.cloudfront true"
    - "aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths \"/*\""
branches:
    only:
        - master
notifications:
    email:
        on_failure: always
